### ISSUE TITLE
"Buffer has wrong number of dimensions (expected 1, got 2)" error when running demo on Replicate

### ISSUE THREAD

**Issue by AVTV64** [Wendison/VQMIVC#12]
Hello, when I run the demo on Replicate with 2 custom files I get a "Buffer has wrong number of dimensions (expected 1, got 2)" error. This is the error log:
Running predict()...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cog/server/redis_queue.py", line 132, in start
    self.handle_message(response_queue, message, cleanup_functions)
  File "/usr/local/lib/python3.6/site-packages/cog/server/redis_queue.py", line 188, in handle_message
    result = run_prediction(self.predictor, inputs, cleanup_functions)
  File "/usr/local/lib/python3.6/site-packages/cog/predictor.py", line 62, in run_prediction
    result = predictor.predict(**inputs)
  File "/usr/local/lib/python3.6/site-packages/cog/input.py", line 80, in wraps
    return f(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cog/input.py", line 80, in wraps
    return f(self, **kwargs)
  File "/src/predict.py", line 113, in predict
    src_mel, src_lf0 = extract_logmel(src_wav_path, self.mean, self.std)
  File "/src/predict.py", line 49, in extract_logmel
    f0, timeaxis = pw.dio(wav.astype("float64"), fs, frame_period=frame_period)
  File "pyworld/pyworld.pyx", line 93, in pyworld.pyworld.dio
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

**Comment by Wendison** [comment]
Hi, please check the number of channels of your wav file, the number of channels should be 1.

**Comment by AVTV64** [comment]
Thanks, changing stereo to mono works.
