### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by Hu-chengyang** [Wendison/VQMIVC#33]
Dear PHD:
I try to train a vocoder, and I have installed parallelwavegan,and I run the command: run.sh,however it came out with the traceback:
Traceback (most recent call last):
  File "/home/liyp/anaconda3/envs/xll/bin/parallel-wavegan-preprocess", line 11, in <module>
    load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-preprocess')()
  File "/data2/hcy/VQMIVC-main/vocoder/ParallelWaveGAN/parallel_wavegan/bin/preprocess.py", line 186, in main
    ), f"{utt_id} seems to have a different sampling rate."

I find that the sampling rate is 24000hz,however the sampling rate of the VQMIVC is 16000,could you tell me how to modify the sampling rate?

**Comment by Wendison** [comment]
Hi, you can use `sox` or `ffmpeg` to change the sampling rate of wavs, e.g., 
`sox {original_24kHz.wav} -r 16000 {converted.wav}`

**Comment by Hu-chengyang** [comment]
Thank you and I have successfully run the parallelwavegan,however,in config.yml,my distributed is false and the distributed in yours is true,can you tell me how to modify the distributed?

**Comment by Hu-chengyang** [comment]
Do it mean if I do not install apex so that I will not be able to use distributed training, and the distributed in the config.yml will be false?
